### PR TITLE
Added benchmarks.

### PR DESCRIPTION
**Pull request by bwplotka**

### CODE REVIEW

**Comment by bwplotka** [comment]
How to invoke: `/tmp/___2BenchmarkExport_in_github_com_thanos_community_obslytics_cmd_obslytics.test -test.v -test.paniconexit0 -test.bench ^\QBenchmarkExport\E$ -test.run ^$ -test.benchtime 1s`

**Comment by bwplotka** [comment]
From CLI: ` go test -bench ^BenchmarkExport$ -run ^$ -benchtime 20s -memprofile mem.out ./cmd/obslytics/... `

**Comment by bwplotka** [comment]
For me it shows

```
go test -bench ^BenchmarkExport$ -run ^$ -benchtime 20s -memprofile mem.out ./cmd/obslytics/...
goos: linux
goarch: amd64
pkg: github.com/thanos-community/obslytics/cmd/obslytics
cpu: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
BenchmarkExport/1000_series_with_100_labels_with_millions_samples-12                 222         100568091 ns/op        68724755 B/op     219162 allocs/op
PASS
ok      github.com/thanos-community/obslytics/cmd/obslytics     33.456s

```

**Comment by bwplotka** [comment]
`go tool pprof -http=:8081 mem.out `

**Comment by bwplotka** [comment]
benchcmp/benchstat

**Review by anishasthana — APPROVED** [review]
Benchmarks ran successfully on my system. :ship:

**Pull request merged**
